/**
 * @file test_device_nvs_integration.c
 * @brief Integration tests for device_info + nvs_manager interaction
 *
 * These tests verify that the device_info component correctly reads
 * and writes data through the nvs_manager component.
 *
 * Copyright (c) 2025 Arttu Tuominen. All rights reserved.
 *
 * This software is licensed under commercial terms.
 * See LICENSE file for complete license terms.
 *
 * NOTICE: This file contains proprietary information. Unauthorized
 * distribution or use is strictly prohibited.
 */

#include <string.h>
#include <stdlib.h>
#include "unity.h"
#include "esp_log.h"
#include "device_info.h"
#include "nvs_manager.h"
#include "common_defs.h"

static const char *TEST_TAG = "TEST_DEVICE_NVS";

static const char *TEST_SSID     = "TestNetwork";
static const char *TEST_PASSWORD = "TestPassword123";

/**
 * @brief Test that device_manager_save_device_info persists data readable via nvs_manager
 */
void test_device_manager_save_info(void)
{
  ESP_LOGI(TEST_TAG, "Testing device manager save info");

  nvs_manager_delete_wifi_credentials();

  device_manager_save_device_info(TEST_SSID, TEST_PASSWORD);

  char retrieved_ssid[MAX_SSID_LEN]         = {0};
  char retrieved_password[MAX_PASSWORD_LEN] = {0};

  esp_err_t result = nvs_manager_get_wifi_credentials(
    retrieved_ssid, sizeof(retrieved_ssid),
    retrieved_password, sizeof(retrieved_password));

  TEST_ASSERT_EQUAL(ESP_OK, result);
  TEST_ASSERT_EQUAL_STRING(TEST_SSID, retrieved_ssid);
  TEST_ASSERT_EQUAL_STRING(TEST_PASSWORD, retrieved_password);

  char device_name[MAX_DEVICE_NAME_LEN] = {0};
  char device_id[MAX_DEVICE_ID_LEN]     = {0};

  result = nvs_manager_get_device_info(
    device_name, sizeof(device_name),
    device_id, sizeof(device_id));

  TEST_ASSERT_EQUAL(ESP_OK, result);
  TEST_ASSERT_GREATER_THAN(0, strlen(device_name));
  TEST_ASSERT_GREATER_THAN(0, strlen(device_id));
  TEST_ASSERT_NOT_NULL(strstr(device_name, "ESP-C6-Light"));
  TEST_ASSERT_EQUAL(8, strlen(device_id));
}

/**
 * @brief Test that a second call to device_manager_save_device_info does not
 *        overwrite already-generated device info stored via nvs_manager
 */
void test_device_manager_save_existing(void)
{
  ESP_LOGI(TEST_TAG, "Testing device manager save with existing data");

  device_manager_save_device_info(TEST_SSID, TEST_PASSWORD);

  char original_name[MAX_DEVICE_NAME_LEN] = {0};
  char original_id[MAX_DEVICE_ID_LEN]     = {0};

  nvs_manager_get_device_info(
    original_name, sizeof(original_name),
    original_id, sizeof(original_id));

  device_manager_save_device_info("NewSSID", "NewPassword");

  char new_name[MAX_DEVICE_NAME_LEN] = {0};
  char new_id[MAX_DEVICE_ID_LEN]     = {0};

  nvs_manager_get_device_info(
    new_name, sizeof(new_name),
    new_id, sizeof(new_id));

  TEST_ASSERT_EQUAL_STRING(original_name, new_name);
  TEST_ASSERT_EQUAL_STRING(original_id, new_id);
}

/**
 * @brief Test that the device ID generated by device_manager and stored in
 *        nvs_manager matches the 8-char hex format
 */
void test_device_id_format(void)
{
  ESP_LOGI(TEST_TAG, "Testing device ID format");

  nvs_manager_delete_wifi_credentials();
  device_manager_save_device_info(TEST_SSID, TEST_PASSWORD);

  char device_name[MAX_DEVICE_NAME_LEN] = {0};
  char device_id[MAX_DEVICE_ID_LEN]     = {0};

  esp_err_t result = nvs_manager_get_device_info(
    device_name, sizeof(device_name),
    device_id, sizeof(device_id));

  TEST_ASSERT_EQUAL(ESP_OK, result);
  TEST_ASSERT_EQUAL(8, strlen(device_id));

  for (int i = 0; i < 8; i++) {
    char c      = device_id[i];
    bool is_hex = (c >= '0' && c <= '9') ||
                  (c >= 'A' && c <= 'F') ||
                  (c >= 'a' && c <= 'f');
    TEST_ASSERT_TRUE(is_hex);
  }

  ESP_LOGI(TEST_TAG, "Generated device ID: %s", device_id);
}

/**
 * @brief Test that the device name stored by device_manager follows the
 *        expected "ESP-C6-Light-XXXXXXXX" pattern
 */
void test_device_name_format(void)
{
  ESP_LOGI(TEST_TAG, "Testing device name format");

  nvs_manager_delete_wifi_credentials();
  device_manager_save_device_info(TEST_SSID, TEST_PASSWORD);

  char device_name[MAX_DEVICE_NAME_LEN] = {0};
  char device_id[MAX_DEVICE_ID_LEN]     = {0};

  esp_err_t result = nvs_manager_get_device_info(
    device_name, sizeof(device_name),
    device_id, sizeof(device_id));

  TEST_ASSERT_EQUAL(ESP_OK, result);
  TEST_ASSERT_NOT_NULL(strstr(device_name, "ESP-C6-Light-"));

  char expected[sizeof("ESP-C6-Light-") + MAX_DEVICE_ID_LEN + 1];
  snprintf(expected, sizeof(expected), "ESP-C6-Light-%s", device_id);
  TEST_ASSERT_EQUAL_STRING(expected, device_name);

  ESP_LOGI(TEST_TAG, "Generated device name: %s", device_name);
}

/**
 * @brief Test repeated device_manager + nvs_manager round-trips stay consistent
 */
void test_device_multiple_operations(void)
{
  ESP_LOGI(TEST_TAG, "Testing multiple device info operations");

  for (int i = 0; i < 5; i++) {
    nvs_manager_delete_wifi_credentials();

    char test_ssid[32];
    snprintf(test_ssid, sizeof(test_ssid), "TestSSID_%d", i);
    device_manager_save_device_info(test_ssid, TEST_PASSWORD);

    char retrieved_ssid[MAX_SSID_LEN]         = {0};
    char retrieved_password[MAX_PASSWORD_LEN] = {0};

    esp_err_t result = nvs_manager_get_wifi_credentials(
      retrieved_ssid, sizeof(retrieved_ssid),
      retrieved_password, sizeof(retrieved_password));

    TEST_ASSERT_EQUAL(ESP_OK, result);
    TEST_ASSERT_EQUAL_STRING(test_ssid, retrieved_ssid);

    esp_app_desc_t *app_desc = get_firmware_info();
    TEST_ASSERT_NOT_NULL(app_desc);
    free(app_desc);
  }
}
